#!/usr/bin/env python3
"""
synthesize.py — Synthesise Verilog RTL for an FPGA using Quartus Prime.

Usage:
    python3 scripts/synthesize.py <config.synthesize.yml>

The YAML file must contain a top-level 'synthesize' key.  All relative paths
are resolved against the directory containing the YAML file.

If Quartus is not installed the script will generate the TCL script and then
exit with a clear message showing how to run it manually.

Minimal example (my_cpu.synthesize.yml):
    synthesize:
      output-dir: ./build/quartus
      device: 5CSEMA5F31C6
      top: my_cpu
      rtl:
        base-dir: ./rtl
        files:
          - my_pkg.v
          - my_cpu.v
        include-testbench: false
"""

import argparse, glob, os, re, shutil, subprocess, sys

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required.  Run: pip3 install pyyaml", file=sys.stderr)
    sys.exit(1)

def log(msg):   print(f"[synthesize] {msg}")
def die(msg):   print(f"[synthesize] ERROR: {msg}", file=sys.stderr); sys.exit(1)

def run_cmd(cmd, *, verbose=False, stream=False):
    if verbose:
        log("$ " + " ".join(str(c) for c in cmd))
    if stream:
        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE,
                                stderr=subprocess.STDOUT, text=True)
        output = []
        for line in proc.stdout:
            print(line, end="")
            output.append(line)
        proc.wait()
        return proc.returncode, "".join(output)
    r = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if verbose:
        print(r.stdout, end="")
    return r.returncode, r.stdout

def load_config(yaml_path):
    with open(yaml_path) as f:
        doc = yaml.safe_load(f)
    if not isinstance(doc, dict) or "synthesize" not in doc:
        die(f"'{yaml_path}' must have a top-level 'synthesize' key")
    cfg = doc["synthesize"]
    base = os.path.dirname(os.path.abspath(yaml_path))
    def rel(path):
        if not path: return path
        return path if os.path.isabs(path) else os.path.normpath(os.path.join(base, path))

    output_dir = rel(cfg.get("output-dir", "./build/quartus"))
    device     = cfg.get("device", "") or die("'device' (FPGA part number) is required")
    top        = cfg.get("top", "")    or die("'top' (top-level module name) is required")

    rtl = cfg.get("rtl", {}) or {}
    rtl_base        = rel(rtl.get("base-dir", "")) or ""
    rtl_files_list  = rtl.get("files", []) or []
    if not rtl_files_list:
        die("'rtl.files' is required and must be a non-empty list")
    # Resolve each file relative to base-dir (or YAML dir if base-dir not set)
    rtl_files = []
    for f in rtl_files_list:
        if rtl_base and not os.path.isabs(f):
            fpath = os.path.normpath(os.path.join(rtl_base, f))
        else:
            fpath = rel(f) if not os.path.isabs(f) else f
        if not os.path.isfile(fpath):
            die(f"RTL file not found: {fpath}")
        rtl_files.append(fpath)
    include_tb      = bool(rtl.get("include-testbench", False))
    extra_files     = [rel(f) for f in (rtl.get("extra-files", []) or [])]

    quartus = cfg.get("quartus", {}) or {}
    quartus_bin = rel(quartus.get("bin", "")) or ""

    return {
        "output_dir":  output_dir,
        "device":      device,
        "top":         top,
        "rtl_files":   rtl_files,
        "include_tb":  include_tb,
        "extra_files": extra_files,
        "quartus_bin": quartus_bin,
    }

def filter_rtl_files(rtl_files, extra_files, include_tb):
    """Filter RTL files and append extra files."""
    tb_pattern = re.compile(r"(_tb|_testbench|_sim)\.(v|sv|vhd|vhdl)$", re.IGNORECASE)
    filtered = []
    for f in rtl_files:
        if not include_tb and tb_pattern.search(f):
            continue
        filtered.append(f)
    for f in extra_files:
        if os.path.isfile(f) and f not in filtered:
            filtered.append(f)
    return filtered

def find_quartus_sh(quartus_bin_override):
    """Locate quartus_sh binary."""
    if quartus_bin_override:
        candidate = os.path.join(quartus_bin_override, "quartus_sh")
        if os.path.isfile(candidate):
            return candidate
    rootdir = os.environ.get("QUARTUS_ROOTDIR", "")
    if rootdir:
        candidate = os.path.join(rootdir, "bin", "quartus_sh")
        if os.path.isfile(candidate):
            return candidate
    found = shutil.which("quartus_sh")
    return found  # may be None

def generate_tcl(project_name, top, device, rtl_files, output_dir):
    """Generate a Quartus TCL compilation script."""
    lines = [
        f"# Auto-generated by synthesize.py",
        f"load_package flow",
        f"",
        f"set project_name {project_name}",
        f"set output_dir   {output_dir}",
        f"",
        f"if {{[project_exists $project_name]}} {{",
        f"    project_open -revision $project_name $project_name -force",
        f"}} else {{",
        f"    project_new -revision $project_name $project_name",
        f"}}",
        f"",
        f"set_global_assignment -name FAMILY \"Cyclone V\"",
        f"set_global_assignment -name DEVICE {device}",
        f"set_global_assignment -name TOP_LEVEL_ENTITY {top}",
        f"",
    ]
    ext_map = {
        ".v":    "VERILOG_FILE",
        ".sv":   "SYSTEMVERILOG_FILE",
        ".vhd":  "VHDL_FILE",
        ".vhdl": "VHDL_FILE",
        ".qip":  "QIP_FILE",
        ".sdc":  "SDC_FILE",
    }
    for f in rtl_files:
        ext  = os.path.splitext(f)[1].lower()
        asgn = ext_map.get(ext, "VERILOG_FILE")
        lines.append(f"set_global_assignment -name {asgn} {f}")

    # Add search path for includes (for .vh header files)
    rtl_dir = os.path.dirname(rtl_files[0]) if rtl_files else ".."
    include_dir = os.path.join(rtl_dir, "include")
    lines.insert(len(lines) - 3, f"set_global_assignment -name SEARCH_PATH {include_dir}")
    lines.insert(len(lines) - 3, f"")

    lines += [
        f"",
        f"execute_flow -compile",
        f"project_close",
    ]
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(
        description="Synthesise RTL for an FPGA from a YAML config file.")
    parser.add_argument("config", help="Path to a .synthesize.yml file")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()
    if not os.path.isfile(args.config):
        die(f"Config file not found: {args.config}")

    cfg = load_config(args.config)
    output_dir = cfg["output_dir"]
    top        = cfg["top"]
    device     = cfg["device"]
    os.makedirs(output_dir, exist_ok=True)

    # Filter and collect RTL files
    rtl_files = filter_rtl_files(cfg["rtl_files"], cfg["extra_files"], cfg["include_tb"])
    if not rtl_files:
        die("No RTL files to synthesize")
    log(f"Found {len(rtl_files)} RTL source file(s):")
    for f in rtl_files:
        log(f"  {f}")

    # Generate TCL script
    project_name = top
    project_dir  = os.path.join(output_dir, project_name)
    os.makedirs(project_dir, exist_ok=True)
    tcl_path = os.path.join(project_dir, f"{project_name}_build.tcl")
    tcl_content = generate_tcl(project_name, top, device, rtl_files, project_dir)
    with open(tcl_path, "w") as f:
        f.write(tcl_content)
    log(f"TCL script written → {tcl_path}")

    # Find Quartus
    quartus_sh = find_quartus_sh(cfg["quartus_bin"])
    if not quartus_sh:
        log("Quartus Prime not found on this machine.")
        log("To synthesise manually, install Quartus and run:")
        print(f"  cd {project_dir}")
        print(f"  quartus_sh -t {tcl_path}")
        return

    # Run synthesis
    log(f"Running synthesis: {quartus_sh} -t {tcl_path}")
    rc, out = run_cmd([quartus_sh, "-t", tcl_path], verbose=args.verbose, stream=True)
    if rc != 0:
        die(f"Quartus synthesis failed (exit {rc})")
    log("Synthesis complete")

if __name__ == "__main__":
    main()
