// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// Copyright (c) 2026 Analog Devices, Inc.
//===-- MYISAInstPrinter.h - MYISA MCInst to assembly --------*- C++ -*-===//
//
// WHAT THIS FILE IS:
//   Declares the MYISAInstPrinter class — the component that converts MCInst
//   objects (low-level instruction representation) into human-readable assembly
//   text. This is the very last step in the compilation pipeline before the
//   assembly string is written to the output file.
//
// WHY IT MUST EXIST:
//   MCInst objects contain opcodes and operands as numbers and enum values.
//   The InstPrinter renders them into the target's assembly syntax:
//     MCInst{opcode=MYISA::ADD_rrr, ops=[R8, R9, R10]}
//     → "ADD\tr8, r9, r10"
//   Without this, LLVM would have no way to produce readable assembly output.
//   The `llc -march=myisa` and `clang --target=myisa -S` commands both
//   ultimately call this printer.
//
// WHAT EACH METHOD DOES:
//   printInstruction() [auto-generated]:
//     The main printing function, auto-generated by TableGen from the
//     AsmString fields in MYISAInstrInfo.td. For each instruction, it
//     prints the mnemonic and calls printOperand()/printMemOperand() for
//     each operand placeholder ($rd, $rs1, $src, etc.).
//
//   getMnemonic() [auto-generated]:
//     Returns the mnemonic string for a given MCInst (e.g., "ADD", "LOAD").
//
//   getRegisterName() [auto-generated, static]:
//     Converts a register enum (MYISA::R8) to its assembly name ("r8").
//
//   printInst():
//     Top-level entry point called by the MCStreamer. Delegates to the
//     auto-generated printInstruction(), then appends any annotation.
//
//   printOperand() [3-arg]:
//     Prints a single operand: registers as names, immediates as numbers,
//     expressions (symbols) via their print() method.
//
//   printOperand() [4-arg]:
//     Same as above but takes an instruction address for PC-relative printing.
//     Currently delegates to the 3-arg version (no PC adjustment).
//
//   printMemOperand():
//     Prints a memory operand in "[reg + offset]" format. Handles the two
//     sub-operands of the memsrc composite (base register + offset immediate).
//
// WHAT COULD BE ADDED:
//   - printBranchTarget(): print PC-relative targets as labels or offsets
//   - printImmOperand(): custom immediate formatting (hex, decimal, etc.)
//   - Multiple syntax variants (e.g., AT&T vs Intel style)
//   - Alias printing: NOP instead of "ADD r0, r0, r0"
//   - printRegName() override for custom register name formatting
//   - Annotation support for profiling data or optimization hints
//
//===----------------------------------------------------------------------===//
#ifndef LLVM_LIB_TARGET_MYISA_MCTARGETDESC_MYISAINSTPRINTER_H
#define LLVM_LIB_TARGET_MYISA_MCTARGETDESC_MYISAINSTPRINTER_H

#include "llvm/MC/MCInstPrinter.h"

namespace llvm {

class MYISAInstPrinter : public MCInstPrinter {
public:
  MYISAInstPrinter(const MCAsmInfo &MAI, const MCInstrInfo &MII,
                    const MCRegisterInfo &MRI)
      : MCInstPrinter(MAI, MII, MRI) {}

  // --- Auto-generated methods (from MYISAGenAsmWriter.inc) ---

  // Prints the complete instruction (mnemonic + operands) using the
  // AsmString templates from MYISAInstrInfo.td.
  void printInstruction(const MCInst *MI, uint64_t Address, raw_ostream &O);

  // Returns the mnemonic string and encoding info for an instruction.
  std::pair<const char *, uint64_t> getMnemonic(const MCInst *MI) override;

  // Converts a register enum value to its assembly-language name.
  // E.g., MYISA::R8 → "r8", MYISA::R30 → "r30"
  static const char *getRegisterName(MCRegister Reg);

  // --- MCInstPrinter interface ---

  // Top-level printing entry point. Called by MCStreamer::emitInstruction().
  // Prints the instruction followed by any annotation string.
  void printInst(const MCInst *MI, uint64_t Address, StringRef Annot,
                 const MCSubtargetInfo &STI, raw_ostream &O) override;

  // --- Operand printing methods ---
  // Called from the generated printInstruction() for each operand placeholder.

  // Print a single operand (register, immediate, or expression).
  void printOperand(const MCInst *MI, unsigned OpNo, raw_ostream &O);

  // Same as above but with instruction address (for PC-relative operands).
  void printOperand(const MCInst *MI, uint64_t Address, unsigned OpNo,
                    raw_ostream &O);

  // Print a memory operand as "[base + offset]" or "[base]" if offset=0.
  // The PrintMethod="printMemOperand" in MYISAInstrInfo.td triggers this.
  void printMemOperand(const MCInst *MI, int OpNum, raw_ostream &O);
};

} // end namespace llvm

#endif
