// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// Copyright (c) 2026 Analog Devices, Inc.
//===-- MYISASubtarget.h - MYISA Subtarget --------------------*- C++ -*-===//
//
// WHAT THIS FILE IS:
//   Declares the MYISASubtarget class — the central "wiring hub" that holds
//   all backend sub-components and provides accessors to them. Every part of
//   the backend that needs InstrInfo, RegisterInfo, FrameLowering, or
//   TargetLowering goes through the Subtarget.
//
// WHY IT MUST EXIST:
//   LLVM's code generator accesses target-specific information through a
//   chain: TargetMachine → Subtarget → {InstrInfo, RegInfo, etc.}. The
//   Subtarget is the nexus. It also:
//     1. Parses feature strings (-mattr=+feature) into boolean flags
//     2. Provides the getInstrInfo(), getRegisterInfo(), etc. overrides
//        that the generic CodeGen framework calls hundreds of times
//     3. Inherits from MYISAGenSubtargetInfo (auto-generated) which
//        implements ParseSubtargetFeatures() from the .td feature defs
//
// WHAT EACH PART DOES:
//   - HasNone flag: placeholder for subtarget features (no real features yet)
//   - MYISAInstrInfo InstrInfo: instruction info (copyPhysReg, spill/reload)
//   - MYISARegisterInfo RegInfo: register info (reserved regs, frame elim)
//   - MYISAFrameLowering FrameLowering: prologue/epilogue generation
//   - MYISATargetLowering TLInfo: legalization and call lowering
//   - SelectionDAGTargetInfo TSInfo: DAG-level target info (usually empty)
//   - Accessor overrides: let LLVM's generic code reach each sub-component
//   - ParseSubtargetFeatures(): generated from .td, sets feature flags
//
// WHAT COULD BE ADDED:
//   - Feature flag booleans (HasHWDiv, HasMAC, HasSIMD, etc.) that control
//     which instructions are available and which operations expand to libcalls
//   - Multiple subtarget configurations for different CPU variants
//   - getPostRAMutations() for post-RA scheduling customization
//   - enablePostRAScheduler() override to enable/disable post-RA scheduling
//   - useAA() override to enable alias analysis during scheduling
//   - getSpecialAddressLatency() for memory access cost modeling
//
//===----------------------------------------------------------------------===//
#ifndef LLVM_LIB_TARGET_MYISA_MYISASUBTARGET_H
#define LLVM_LIB_TARGET_MYISA_MYISASUBTARGET_H

#include "MYISAFrameLowering.h"
#include "MYISAISelLowering.h"
#include "MYISAInstrInfo.h"
#include "MYISARegisterInfo.h"
#include "llvm/CodeGen/SelectionDAGTargetInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DataLayout.h"

// Include the auto-generated subtarget feature enum (MYISA::FeatureNone, …)
// GET_SUBTARGETINFO_ENUM defines the enum values for each SubtargetFeature.
#define GET_SUBTARGETINFO_ENUM
#include "MYISAGenSubtargetInfo.inc"

// GET_SUBTARGETINFO_HEADER declares the MYISAGenSubtargetInfo base class
// with ParseSubtargetFeatures() and feature-query methods.
#define GET_SUBTARGETINFO_HEADER
#include "MYISAGenSubtargetInfo.inc"

namespace llvm {

class MYISASubtarget : public MYISAGenSubtargetInfo {
  // --- Feature flags ---
  // These booleans are set by ParseSubtargetFeatures() based on the user's
  // -mattr= flags. Each corresponds to a SubtargetFeature in MYISA.td.
  // Currently only a placeholder exists.
  bool HasNone = false;

  // --- Sub-component instances ---
  // Each of these is a self-contained object that implements one aspect of
  // the backend. The Subtarget owns them all and provides accessors.
  MYISAInstrInfo InstrInfo;           // Instruction manipulation utilities
  MYISARegisterInfo RegInfo;          // Register file description
  MYISAFrameLowering FrameLowering;   // Prologue/epilogue generation
  MYISATargetLowering TLInfo;         // Legalization and call lowering
  SelectionDAGTargetInfo TSInfo;       // DAG-level target info (minimal)

public:
  // Constructor: called by MYISATargetMachine during initialization.
  // Parses the CPU name and feature string to set feature flags.
  MYISASubtarget(const Triple &TT, const std::string &CPU,
                  const std::string &FS, const TargetMachine &TM);

  // --- Accessors (overrides of TargetSubtargetInfo virtual methods) ---
  // These are called extensively by LLVM's generic codegen infrastructure.

  const MYISAInstrInfo *getInstrInfo() const override { return &InstrInfo; }
  const MYISARegisterInfo *getRegisterInfo() const override { return &RegInfo; }
  const MYISAFrameLowering *getFrameLowering() const override {
    return &FrameLowering;
  }
  const MYISATargetLowering *getTargetLowering() const override {
    return &TLInfo;
  }
  const SelectionDAGTargetInfo *getSelectionDAGInfo() const override {
    return &TSInfo;
  }

  // ParseSubtargetFeatures — Auto-generated by TableGen from MYISA.td's
  // SubtargetFeature definitions. Parses the feature string and sets the
  // corresponding boolean flags (HasNone, etc.).
  void ParseSubtargetFeatures(StringRef CPU, StringRef TuneCPU, StringRef FS);
};

} // end namespace llvm

#endif
